services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root-user
      POSTGRES_PASSWORD: hard-password
      POSTGRES_DB: pos-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  gunicorn:
    build: .
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_NAME=pos-db
      - DB_USER=root-user
      - DB_PASSWORD=hard-password
      - DB_HOST=postgres
      - DB_PORT=5432
  
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - gunicorn

volumes:
  postgres_data:
  static_volume:
  media_volume:
