# Generated by Django 5.1.6 on 2025-04-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reorder_needed',
        ),
    ]
